Student: Skoropad Mykhailo
Group: CE-47
Subject: CSDT

Project name: Sea Battle Game
Programming language: C#

HW interface: I2C
Data driven format: XML

Play modes: Man vs AI, Man vs Man, AI vs AI

AI supports next complexity levels: Random move, Win strategy

Actions: New, Save, Load

The proposal for data driven approach: configuration (saved in configuration file or DB): board size, distance, tool size, win statement, lose statement, AI parameters
